### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by ouchxp** [marianogappa/sql#13]
I like the new feature that allows to have sql as parameter, but the latest binary release does not have it. Could you make a new release please?
![image](https://user-images.githubusercontent.com/1253729/45338629-361e6c80-b5e2-11e8-8b39-e5e01b89e22f.png)

**Comment by marianogappa** [comment]
Will do Nan, sorry! :P I'll implement Goreleaser today at some point.
If you can't wait, you can do `go get -u github.com/marianogappa/sql` and `cd $GOPATH/src/github.com/marianogappa/sql && go install`

**Comment by ouchxp** [comment]
Thanks! I'm using go get right now. However I'm planning to use zplug to manage some binary tools. That's why I'd prefer to have a binary release so that it can be downloaded by zplug directly.

**Comment by marianogappa** [comment]
@ouchxp  https://github.com/MarianoGappa/sql/releases
