### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by marianogappa** [marianogappa/sql#16]
The nature of `sql` makes it cumbersome for testing. We'll probably not test `ssh`, but given that it's used extensively at Movio, it'd be best if it was less scary to makes changes to the code.

**Comment by marianogappa** [comment]
@aidin36 can I get you to test #17 pleeez :)

**Comment by aidin36** [comment]
I ran the tests on my local machine, and briefly looked at the code. All good! :+1:
