### ISSUE TITLE
Follow XDG spec for config files

### ISSUE THREAD

**Issue by lucianjon** [marianogappa/sql#2]
Can't promise it's interesting

For reference: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by marianogappa** [comment]
@lucianjon sorry for taking so long; as you said, there was little incentive to work on this :P

`sql` will now look for `.databases.json` in the following places, in order:
1) `$XDG_CONFIG_HOME/sql/.databases.json` (if set)
2) `$HOME/.config/sql/.databases.json` (if `$XDG_CONFIG_HOME` unset)
3...) each of `$XDG_CONFIG_DIRS` including default `/etc/xdg` (plus `/sql/.databases.json`)
4) `$HOME/.databases.json`

So it follows XDG with a fallback on the existing path, for backwards compatibility and general laziness.

**Comment by marianogappa** [comment]
Fixed in
https://github.com/marianogappa/sql/releases/tag/1.0.2
