### ISSUE TITLE
Usage function doesn't correctly print when called with multiple interpolation arguments

### ISSUE THREAD

**Issue by lucianjon** [marianogappa/sql#4]
As an example:

`Couldn't read [[/Users/lucianj/.databases.json open /Users/lucianj/.databases.json: no such file or directory]] file. err=%!v(MISSING)`

https://github.com/marianogappa/sql/blob/master/usage.go#L11 should be `fmt.Println(fmt.Sprintf(error, args...))`

**Comment by marianogappa** [comment]
OMG who would write `fmt.Println(fmt.Sprintf(error, args))`???

```
37d2dd84 (Mariano Gappa 2016-09-17 21:19:38 +1200 11)       fmt.Println(fmt.Sprintf(error, args))
```

meh

**Comment by marianogappa** [comment]
Solved in
https://github.com/marianogappa/sql/releases/tag/1.0.2
