### ISSUE TITLE
Started processes should be killed on SIGINT

### ISSUE THREAD

**Issue by marianogappa** [marianogappa/sql#7]

**Comment by therealplato** [comment]
https://github.com/marianogappa/sql/pull/9/files

**Comment by marianogappa** [comment]
This is very good stuff! Tests show that even though the ssh processes are indeed killed, the queries on the remote server are not killed. Unfortunately, that detail makes the feature less than ideal. Let's spend a little more time to see if we can change ssh's behaviour on termination. Perhaps a different termination signal does the job.

**Comment by marianogappa** [comment]
I'll merge it and then start testing with `ssh -t -t` to see if the remote mysql processes are terminated.

**Comment by marianogappa** [comment]
It was more complicated than we thought. This is a very insightful response: https://serverfault.com/questions/463366/does-getting-disconnected-from-an-ssh-session-kill-your-programs/463375#463375?newreg=262ab662145f48e6b09d66fe21310cae

The mysql client process will terminate shortly. That doesn't mean at all that the mysql server will abort the query. We can look into a configuration in the mysql client exec call to make it abort queries on HUP, but there is nothing we can do from the ssh command.

**Comment by marianogappa** [comment]
Also I discovered today we can use the `SLEEP(seconds)` function on MariaDB to test this!

```
MariaDB [test]> select sleep(10);
```
10 seconds later…
```
+-----------+
| sleep(10) |
+-----------+
|         0 |
+-----------+
```

**Comment by marianogappa** [comment]
I'm afraid this is a limitation of the `mysql` client; I can validate the queries still live on the server until they finish. Research only points to using `SHOW PROCESSLIST` + `KILL 1234`. We can revise this in the future.
